
(require 'all-the-icons)
(require 'auto-complete)
(require 'cl-lib)
(require 'elpy)
(require 'go-autocomplete)
(require 'go-eldoc)
(require 'helm)
(require 'helm-config)
(require 'helm-projectile)
(require 'jedi)
(require 'ledger-mode)
(require 'nlinum)
(require 'org-bullets)
(require 'package)
(require 'paren)
(require 'popwin)
(require 'web-mode)
(require 'yaml-mode)

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(blink-cursor-mode 1)
(column-number-mode 1)
(line-number-mode 1)
(winner-mode 1)
(projectile-mode 1)
(global-subword-mode 1)
(global-hl-line-mode 1)
(show-paren-mode 1)
(helm-mode 1)
(helm-projectile-on)
(helm-autoresize-mode 1)

(setq user-full-name "Abhinav Pandey")
(setq user-mail-address "abhinav.predicate@gmail.com")

(setq-default truncate-lines t)
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(setq-default cursor-type 'bar)

(setq inhibit-startup-screen t)

(setq mac-command-modifier 'meta)
(setq mac-option-modifier 'super)
(setq mac-control-modifier 'control)
(setq ns-function-modifier 'hyper)

(setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
(setq delete-by-moving-to-trash t)
(setq dired-recursive-deletes t)
(setq backup-by-copying t)
(setq backup-directory-alist '((".*" . "~/.emacs.d/backup")))
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/saves/" t)))
(setq confirm-kill-emacs 'yes-or-no-p)
(setq ring-bell-function 'ignore)
(setq sentence-end-double-space nil)
(setq show-paren-delay 0)
(setq show-paren-style 'parenthesis)
(setq nlinum-format " %d ")
(setq nlinum-highlight-current-line t)

(setq helm-split-window-inside-p t)
(setq helm-autoresize-min-height 20)
(setq helm-autoresize-max-height 20)

(setq org-startup-indented 1)
(setq org-hide-leading-stars 1)
(setq org-return-follows-link 1)
(setq org-image-actual-width nil)
(setq org-src-fontify-natively 1)
(setq org-src-tab-acts-natively 1)
(setq org-edit-src-content-indentation 4)
(setq org-src-window-setup 'current-window)
(setq org-todo-keywords '((sequence "TODO" "PROG" "|" "DONE")))
(setq org-todo-keyword-faces '(("TODO" . (:foreground "red" :underline t))
                               ("PROG" . (:foreground "orange" :underline t))))
(setq org-done-keyword-faces '(("DONE" . (:foreground "green" :underline t))))
(setq org-link-abbrev-alist '(("quasars"  . "file:~/Uber/Quasars/")))

(add-to-list 'default-frame-alist '(height . 71))
(add-to-list 'default-frame-alist '(width . 236))

(set-face-attribute 'font-lock-builtin-face nil :foreground "#00b3b3")
(set-face-attribute 'font-lock-comment-face nil :foreground "#aaaaaa" :slant 'oblique)
(set-face-attribute 'font-lock-constant-face nil :foreground "#e23860")
(set-face-attribute 'font-lock-doc-face nil :foreground "#cccccc" :slant 'italic)
(set-face-attribute 'font-lock-string-face nil :foreground "sienna" :slant 'italic)
(set-face-attribute 'font-lock-variable-name-face nil :foreground "orange")
(set-face-attribute 'org-block-background nil :slant 'italic)
(set-face-attribute 'org-block-begin-line nil :weight 'bold)
(set-face-attribute 'org-block-end-line nil :weight 'bold)
(set-face-attribute 'org-level-1 nil :weight 'bold :foreground "black")
(set-face-attribute 'org-level-2 nil :weight 'bold :foreground "black")
(set-face-attribute 'org-level-3 nil :weight 'bold :foreground "black")
(set-face-attribute 'org-level-4 nil :weight 'bold :foreground "black")
(set-face-attribute 'org-level-5 nil :weight 'bold :foreground "black")
(set-face-attribute 'helm-match nil :weight 'bold)
(set-face-attribute 'show-paren-match nil :weight 'extra-bold :foreground "grey" :background "red")
(set-face-attribute 'nlinum-current-line nil :foreground "red" :weight 'bold)
;; (set-face-attribute 'hl-line nil :background "#fff2cc")

(defun do-nothing() (interactive))

(define-key helm-map (kbd "C-i") 'helm-execute-persistent-action)
(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)

(global-set-key (kbd "C-c c") 'comment-region)
(global-set-key (kbd "C-c u") 'uncomment-region)
(global-set-key (kbd "C-x o") 'ace-window)
(global-set-key (kbd "M-n") (lambda () (interactive) (forward-line 5)))
(global-set-key (kbd "M-p") (lambda () (interactive) (forward-line -5)))
(global-set-key (kbd "C-c t") 'toggle-read-only)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-c h") 'helm-command-prefix)

(global-set-key [wheel-left] 'do-nothing)
(global-set-key [wheel-right] 'do-nothing)
(global-set-key [double-wheel-left] 'do-nothing)
(global-set-key [double-wheel-right] 'do-nothing)
(global-set-key [triple-wheel-left] 'do-nothing)
(global-set-key [triple-wheel-right] 'do-nothing)

(add-to-list 'auto-mode-alist '("\.yml$" . yaml-mode)) ; yaml files
(add-to-list 'auto-mode-alist '("\.asm$" . asm86-mode)) ; asm 86 machine files
(add-to-list 'auto-mode-alist '("\.html$" . web-mode)) ; html files
(add-to-list 'auto-mode-alist '("\.css$" . web-mode)) ; css files
(add-to-list 'auto-mode-alist '("\.scss$" . web-mode)) ; scss files
(add-to-list 'auto-mode-alist '("\.js$" . rjsx-mode)) ; javascript files
(add-to-list 'auto-mode-alist '("\.ledger$" . ledger-mode)) ; ledger files
(add-to-list 'auto-mode-alist '("\.m$" . octave-mode)) ; octave or matlab files

(add-hook 'find-file-hook (lambda () (setq buffer-read-only t)))
(add-hook 'before-save-hook (lambda () (setq buffer-read-only t)))
(add-hook 'before-save-hook 'delete-trailing-whitespace)
(add-hook 'prog-mode-hook (lambda () (setq show-trailing-whitespace t)))
(add-hook 'prog-mode-hook 'nlinum-mode)

(popwin-mode 1)
(push '("^\*helm.+\*$" :regexp t) popwin:special-display-config)
(push '("^\*vc.+\*$" :regexp t) popwin:special-display-config)
(add-hook 'helm-after-initialize-hook
          (lambda ()
            (popwin:display-buffer helm-buffer t)
            (popwin-mode -1)))
(add-hook 'helm-cleanup-hook
          (lambda ()
            (popwin-mode 1)))

(defun go-mode-setup ()
  (setq-local tab-width 2)
  (setq-local gofmt-command "goimports")
  (local-set-key (kbd "M-.") 'godef-jump)
  (local-set-key (kbd "M-,") 'pop-tag-mark)
  (setenv "GOPATH" "/Users/abhinav.pandey/gocode")
  (add-to-list 'exec-path "Users/abhinav.pandey/gocode/bin")
  (go-eldoc-setup)
  (add-hook 'before-save-hook 'gofmt-before-save))
(add-hook 'go-mode-hook 'go-mode-setup)

(defun rjsx-mode-setup()
  (tern-mode t)
  (eval-after-load 'tern
    '(progn (require 'tern-auto-complete) (tern-ac-setup))))
(autoload 'tern-mode "tern.el" nil t)
(add-hook 'rjsx-mode-hook 'rjsx-mode-setup)

(defun python-mode-setup()
  (setq-local py-use-font-lock-doc-face-p t)
  (setq-local elpy-rpc-timeout 10)
  (setq-local elpy-rpc-backend "jedi")
  (setq-local jedi:complete-on-dot t)
  (add-to-list 'ac-sources 'ac-source-jedi-direct)
  (delete 'elpy-module-highlight-indentation elpy-modules)
  (delete 'elpy-module-django elpy-modules)
  (delete 'elpy-module-yasnippet elpy-modules)
  (elpy-enable)
  (flymake-mode)
  (local-set-key (kbd "M-.") 'jedi:goto-definition)
  (local-set-key (kbd "M-,") 'jedi:goto-definition-pop-marker))
(add-hook 'python-mode-hook 'jedi:setup)
(add-hook 'python-mode-hook 'python-mode-setup)

(defun set-exec-path-from-shell-PATH ()
  (let ((path-from-shell
         (replace-regexp-in-string
          "[ \t\n]*$"
          ""
          (shell-command-to-string "$SHELL --login -i -c 'echo $PATH'"))))
    (setenv "PATH" path-from-shell)
    (setq eshell-path-env path-from-shell)
    (setq exec-path (split-string path-from-shell path-separator)))
  (exec-path-from-shell-initialize))
(when window-system (set-exec-path-from-shell-PATH))

(defun org-mode-setup ()
  (org-bullets-mode 1)
  (org-indent-mode 1)
  (visual-line-mode 1))
(add-hook 'org-mode-hook 'org-mode-setup)
